# Put this file at: .github/workflows/extract-workspace-8137748c-3c97-4663-99b9-d0a3cb469226.yml
name: Extract workspace tar

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract:
    name: Extract tar and commit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true
    - name: Show current files
      run: ls -la
    - name: Create extraction directory
      run: mkdir -p extracted-workspace-8137748c-3c97-4663-99b9-d0a3cb469226
    - name: Extract tar (if present)
      run: |
        TAR="workspace-8137748c-3c97-4663-99b9-d0a3cb469226.tar"
        TARGET_DIR="extracted-workspace-8137748c-3c97-4663-99b9-d0a3cb469226"
        if [ -f "$TAR" ]; then
          echo "Found $TAR, extracting to $TARGET_DIR"
          # try to extract; keep going if some members already exist
          tar -xvf "$TAR" -C "$TARGET_DIR" || true
        else
          echo "Tar file not found: $TAR"
          exit 1
        fi
    - name: Commit extracted files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add extracted-workspace-8137748c-3c97-4663-99b9-d0a3cb469226 || true
        if git status --porcelain | grep . >/dev/null; then
          git commit -m "Extract workspace tar: workspace-8137748c-3c97-4663-99b9-d0a3cb469226.tar" || true
          git push
        else
          echo "No changes to commit"
        fi